/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fi.helsinki.cs.nero.ui;

import fi.helsinki.cs.nero.data.Person;
import fi.helsinki.cs.nero.event.NeroObserverTypes;
import fi.helsinki.cs.nero.logic.Session;
import java.sql.SQLException;
import java.util.HashMap;

/**
 *
 * @author ssinisal
 */
public class PersonInfoFrame extends javax.swing.JFrame {

    /**
     * Creates new form PersonInfoFrame
     */
    private Person person;
    private boolean newPerson;
    private Session session;
    private HashMap<String, String> henkiloHash;
    
    public PersonInfoFrame(Session session, Person person) {
        initComponents();
        this.person = person;
        this.newPerson = false;
        this.session = session;

        htunnusField.setText(person.getPersonID());
        etunimiField.setText(person.getEtunimi());
        sukunimiField.setText(person.getSukunimi());
        huoneField.setText(person.getRoom());
        
        aktiivinenField.setText(person.getActivity());
        hetuField.setText(person.getHetu());
        oppiarvoField.setText(person.getOppiarvo());
        titteliField.setText(person.getTitteli());
        tyopuhelinField.setText(person.getWorkPhone());
        kotipuhelinField.setText(person.getHomePhone());
        kannykkaField.setText(person.getKannykka());
        katuosoiteField.setText(person.getAddress());
        postinumeroField.setText(person.getPostnumber());
        postitoimipaikkaField.setText(person.getPostitoimiPaikka());
        
        sahkopostiField.setText(person.getSahkoposti());
        hallinnollinenkommenttiField.setText(person.getHallinnollinenKommentti());
        
        ktunnusField.setText(person.getkTunnus());
        postilokeroField.setText(person.getPostilokeroHuone());            
        tyosuhdeField.setText(person.getHyTyosuhde());
        puhelinluettelossaField.setText(person.getHyPuhelinluettelossa());
        
        this.setSize(610, 400);
        MoreField.setVisible(false);
        this.setVisible(true);
    }
    
    public PersonInfoFrame(Session session) {
        initComponents();
        this.newPerson = true;
        this.session = session;
        
        this.setSize(680, 400);
        MoreField.setVisible(false);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etunimiField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        huoneField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ktunnusField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        postilokeroField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        MoreButton = new javax.swing.JToggleButton();
        aktiivinenField = new javax.swing.JTextField();
        CancelButton = new javax.swing.JButton();
        MoreField = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        oppiarvoField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tyosuhdeField = new javax.swing.JTextField();
        hetuField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        katuosoiteField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        postinumeroField = new javax.swing.JTextField();
        postitoimipaikkaField = new javax.swing.JTextField();
        sahkopostiField = new javax.swing.JTextField();
        hallinnollinenkommenttiField = new javax.swing.JTextField();
        puhelinluettelossaField = new javax.swing.JTextField();
        htunnusField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        sukunimiField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        titteliField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        kannykkaField = new javax.swing.JTextField();
        kotipuhelinField = new javax.swing.JTextField();
        tyopuhelinField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        errorMessageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("tietoruutu");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);

        jLabel1.setText("Etunimi");

        jLabel2.setText("Huone");

        jLabel3.setText("Aktiivinen (K/E)");

        jLabel4.setText("Käyttäjätunnus");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Postilokerohuone");

        MoreButton.setText("Näytä lisätiedot");
        MoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoreButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Oppiarvo");

        jLabel7.setText("Työsuhde");

        jLabel8.setText("hetu");

        jLabel9.setText("Katuosoite");

        jLabel10.setText("Postinumero");

        jLabel11.setText("H_tunnus");

        jLabel12.setText("Puhelinluettelossa (K/E)");

        jLabel13.setText("Hallinnollinen kommentti");

        jLabel14.setText("Sähköposti");

        jLabel15.setText("Postitoimipaikka");

        javax.swing.GroupLayout MoreFieldLayout = new javax.swing.GroupLayout(MoreField);
        MoreField.setLayout(MoreFieldLayout);
        MoreFieldLayout.setHorizontalGroup(
            MoreFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MoreFieldLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MoreFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(postinumeroField, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oppiarvoField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hetuField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tyosuhdeField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(katuosoiteField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(26, 26, 26)
                .addGroup(MoreFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MoreFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(htunnusField, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                        .addComponent(puhelinluettelossaField)
                        .addComponent(hallinnollinenkommenttiField)
                        .addComponent(sahkopostiField)
                        .addComponent(postitoimipaikkaField))
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MoreFieldLayout.setVerticalGroup(
            MoreFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MoreFieldLayout.createSequentialGroup()
                .addGroup(MoreFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MoreFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oppiarvoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(htunnusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MoreFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MoreFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tyosuhdeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puhelinluettelossaField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MoreFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13))
                .addGap(4, 4, 4)
                .addGroup(MoreFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hallinnollinenkommenttiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hetuField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(MoreFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MoreFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(katuosoiteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sahkopostiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MoreFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MoreFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(postitoimipaikkaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(postinumeroField)))
        );

        jLabel16.setText("Sukunimi");

        jLabel17.setText("Titteli");

        jLabel18.setText("kännykkä");

        jLabel20.setText("kotipuhelin");

        jLabel21.setText("työpuhelin");

        errorMessageLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorMessageLabel.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kotipuhelinField)
                            .addComponent(ktunnusField, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(aktiivinenField, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(huoneField, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(etunimiField, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel20))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(postilokeroField)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel5)
                            .addComponent(jLabel16)
                            .addComponent(sukunimiField, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel21))
                            .addComponent(titteliField)
                            .addComponent(kannykkaField)
                            .addComponent(tyopuhelinField))
                        .addGap(18, 18, 18)
                        .addComponent(MoreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(MoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(7, 7, 7)
                                .addComponent(etunimiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(huoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aktiivinenField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ktunnusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel20))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(7, 7, 7)
                                .addComponent(sukunimiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(postilokeroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(titteliField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kannykkaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel21)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kotipuhelinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tyopuhelinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(MoreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(errorMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MoreButton))
                    .addComponent(CancelButton, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        //nullpointer jos hashmapin avainarvo ei osoita mihinkään (hytyosuhde, aktiivinen, hypuhelinluettelossa)
        //kentät joita ei kuulu muuttaa: huone? , , , , , 
        errorMessageLabel.setText("");
        henkiloHash = new HashMap<String, String>();
        
        henkiloHash.put("htunnus", htunnusField.getText());
        henkiloHash.put("kokonimi", (etunimiField.getText()+" "+sukunimiField.getText()));
        henkiloHash.put("etunimet", etunimiField.getText());
        henkiloHash.put("sukunimi", sukunimiField.getText());
        henkiloHash.put("huone_nro", huoneField.getText());
        henkiloHash.put("kutsumanimi", "");
        henkiloHash.put("aktiivisuus", aktiivinenField.getText());
        henkiloHash.put("hetu", hetuField.getText());
        henkiloHash.put("oppiarvo", oppiarvoField.getText());
        henkiloHash.put("titteli", titteliField.getText());
        henkiloHash.put("puhelin_tyo", tyopuhelinField.getText());
        henkiloHash.put("puhelin_koti", kotipuhelinField.getText());
        henkiloHash.put("kannykka", kannykkaField.getText());
        henkiloHash.put("katuosoite", katuosoiteField.getText());
        henkiloHash.put("postinro", postinumeroField.getText());
        henkiloHash.put("postitoimipaikka", postitoimipaikkaField.getText());
        henkiloHash.put("valvontasaldo", "");
        henkiloHash.put("sahkopostiosoite", sahkopostiField.getText());
        henkiloHash.put("hallinnollinen_kommentti", hallinnollinenkommenttiField.getText());
        henkiloHash.put("opiskelija_kommentti", "");
        henkiloHash.put("ktunnus", ktunnusField.getText());
        henkiloHash.put("postilokerohuone", postilokeroField.getText());
        henkiloHash.put("hy_tyosuhde", tyosuhdeField.getText());
        henkiloHash.put("hy_puhelinluettelossa", puhelinluettelossaField.getText());        
        
        
        this.person = new Person(this.session, henkiloHash, null, null);
        
        //nero dbltä exeptiot handuun, syötteen tarkistus
        try {
            
        if(this.newPerson) {
            person.getSession().saveNewPerson(this.person);
            errorMessageLabel.setText("Henkilö lisätty tietokantaan");
        } else {
            person.getSession().updatePerson(person);
            errorMessageLabel.setText("Muutokset tallennettu tietokantaan");
        }
        
        } catch (SQLException e) { 
            errorMessageLabel.setText("Tietokantavirhe: " + e.getMessage());
        }
        
        //this.dispose();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void MoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoreButtonActionPerformed
        if (MoreField.isVisible()) {
            this.setSize(610, 400);
            MoreField.setVisible(false);
        } else {
            this.setSize(870, 400);
            MoreField.setVisible(true);
        }
    }//GEN-LAST:event_MoreButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new PersonInfoFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JToggleButton MoreButton;
    private javax.swing.JPanel MoreField;
    private javax.swing.JTextField aktiivinenField;
    private javax.swing.JLabel errorMessageLabel;
    private javax.swing.JTextField etunimiField;
    private javax.swing.JTextField hallinnollinenkommenttiField;
    private javax.swing.JTextField hetuField;
    private javax.swing.JTextField htunnusField;
    private javax.swing.JTextField huoneField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField kannykkaField;
    private javax.swing.JTextField katuosoiteField;
    private javax.swing.JTextField kotipuhelinField;
    private javax.swing.JTextField ktunnusField;
    private javax.swing.JTextField oppiarvoField;
    private javax.swing.JTextField postilokeroField;
    private javax.swing.JTextField postinumeroField;
    private javax.swing.JTextField postitoimipaikkaField;
    private javax.swing.JTextField puhelinluettelossaField;
    private javax.swing.JTextField sahkopostiField;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField sukunimiField;
    private javax.swing.JTextField titteliField;
    private javax.swing.JTextField tyopuhelinField;
    private javax.swing.JTextField tyosuhdeField;
    // End of variables declaration//GEN-END:variables
}
